// This is the root layout for the Next.js application
// It defines the overall structure of the HTML document, including the head
// Importing the global CSS files for the application
import "./styles/capstone.css";
import "./styles/styles.css";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import prisma from "./lib/prisma";
import { auth } from "../auth";

export const metadata = {
  title: "Sim Stock",
  description: "Generated by Next.js",
};

import { ReactNode } from "react";

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await auth();

  const user = session?.user?.email
    ? await prisma.user.findUnique({
        where: { email: session.user.email },
        select: { role: true },
      })
    : null;

  const isAdmin = user?.role === "ADMIN";

  return (
    <html>
      <Head>
        <title>SimStock</title>
      </Head>
      <body>
        <div>
          <Link href="/">
            <Image
              className="banner"
              src="/LOGOv1.png"
              alt="Logo"
              width={150}
              height={110}
            />
          </Link>
          <h1>Stock Trading System Simulator</h1>
          <h2>By Team 21</h2>
          <h2>Sam Kline, Michael Lacey, Josien Lajoie</h2>
          <div className="navbar">
          <Link className="logOut" href="/logout"> Log Out </Link>
            <Link className="login" href="/login"> Log In </Link>
            <Link href="/market/schedule">View Schedule</Link>
            <Link href="/market">View Market</Link>
            <div className="dropdown">
              <button className="dropbtn">Account</button>
              <div className="dropdown-content">
                <Link href="/profile">Profile</Link>
                <Link href="/profile/portfolio">Portfolio</Link>
              </div>
            </div>
            {isAdmin && (
              <div className="dropdown">
                <button className="dropbtn">Admin</button>
                <div className="dropdown-content">
                  <Link href="/admin/changeschedule">Change Schedule</Link>
                  <Link href="/admin/marketdata">Create Stock</Link>
                  <Link href="/admin/marketdata">Manage Users</Link>
                </div>
              </div>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
